### ISSUE TITLE
Negative long values throw an exception

### ISSUE THREAD

**Issue by sheitmann** [ullmark/hashids.net#18]
the issue seems to be in a lot of hashid implementations

**Comment by ullmark** [comment]
Yes, hashids doesn't support negative values. As stated in documentation. :)

**Comment by sheitmann** [comment]
oh ok, seems I did not see it.
maybe the method should check for negative long values and throw a meaningful exception and also the method documentation should note this. what you think about?

**Comment by ullmark** [comment]
Yes, to give a slightly longer answer. Some of the others implementations doesn't have all the features C# has. When building the port I thought about using `uint` instead of `int` since that would have made a better APi. The problem is that not a lot of people use `uint` or even know that it exist so I decided against it. Didn't want ppl to do type casting all the time just to use hashids.

Yes, exceptions in hashids have also been a bit of a "should we follow the other libraries or throw exceptions". 

I'll make the documentation more clear! I am currently working (when I have some time over) with converting the entire library to a "Portable Library" to support more platforms.

**Comment by Van-Dame** [comment]
Negative values are still a PITA when using this library. Can you consider extending the usage to uint and ulong parameters as well? Thanks!
