### ISSUE TITLE
Allow specifying ValueTypes for encoding/decoding as data structure

### ISSUE THREAD

**Issue by ChaoticSurfer** [ullmark/hashids.net#51]
It will be performance improvement and for complex types people would be able to use structs, as it makes more sense then using arrays. because structure is fixed, better use value type with fixed signature

**Comment by manigandham** [comment]
Hi @ChaoticSurfer 

I'm not sure I understand. Are you saying you want to be able to pass in a struct with multiple properties instead of an array? The library (and algorithm) supports unlimited parameters in both the encode and decode process so it would require a lot of separate class shapes to recreate all that, and I'm not sure I see the benefit over an array at that point since the allocation is the same.

We can possibly some overloads for a smaller number of encode params but decode is still completely dynamic. Let me know.

**Comment by manigandham** [comment]
Closing for now, feel free to reopen if you have more thoughts on this.
