### ISSUE TITLE
Json support?

### ISSUE THREAD

**Issue by domagojmedo** [ullmark/hashids.net#87]
Would it be possible to have something like https://github.com/Xabaril/AspNetCore.Hashids? 

It works with Json serialization and easily integrates with API

**Comment by manigandham** [comment]
What do you mean? That library already adds automatic serialization with models including JSON output as shown in  the examples on the readme. You can also use the JSON conversion attributes directly on your models if you're serializing directly instead of using model binding.

**Comment by domagojmedo** [comment]
That library does, but last update was in 2021.

Is that something this library can add?

**Comment by manigandham** [comment]
[AspNetCore.Hashids](https://github.com/Xabaril/AspNetCore.Hashids) already uses [ullmark/hashids.net](https://github.com/ullmark/hashids.net) to do the hashing.

It doesn't matter if the last update was in 2021 - if there are any missing features or bugs then they should be fixed in that library.

You can also add or update a reference to _hashids.net_ for the latest version in your project separately.
